# TODO 示例为 H2 数据库，可根据实际情况调整为mysql等数据库
spring:
  datasource:
    url: jdbc:h2:file:./erupt;AUTO_SERVER=TRUE;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2           #H2控制台访问路径
      settings:
        web-allow-others: true
  jpa:
    show-sql: false
    generate-ddl: true
    database: h2